"""TensorRT engine export helper for YOLO models"""

from __future__ import annotations

import argparse
import shutil
import tempfile
from pathlib import Path

try:
    from ultralytics import YOLO
except Exception:
    # keep module importable on systems that only run ONNX inference
    YOLO    = None


def _resolve_engine_path(export_out, model_path: Path) -> Path:
    """Resolve generated engine path from Ultralytics export output"""

    # ultralytics return type can vary by version
    candidate       = None
    try:
        candidate = Path(str(export_out))
    except Exception:
        candidate   = None

    if candidate is not None and candidate.suffix == '.engine' and candidate.exists():
        return candidate

    # common export path when ultralytics does not return explicit location
    default_engine  = model_path.with_suffix('.engine')
    if default_engine.exists():
        return default_engine

    # final fallback for older versions that drop engine in model directory
    hits    = list(model_path.parent.glob('*.engine'))
    if hits:
        hits.sort(key = lambda p: p.stat().st_mtime, reverse = True)
        return hits[0]

    raise FileNotFoundError('Unable to locate generated .engine after export')


def _resolve_onnx_path(model_path: Path) -> Path:
    """Resolve generated ONNX path from an export workspace"""

    default_onnx = model_path.with_suffix('.onnx')
    if default_onnx.exists():
        return default_onnx

    hits = list(model_path.parent.glob('*.onnx'))
    if hits:
        hits.sort(key = lambda p: p.stat().st_mtime, reverse = True)
        return hits[0]

    raise FileNotFoundError('Unable to locate generated .onnx after export')


def _normalize_imgsz(imgsz) -> int | tuple[int, int]:
    """Accept square or explicit (h, w) export sizes"""

    if isinstance(imgsz, (tuple, list)):
        if len(imgsz) != 2:
            raise ValueError(f'imgsz tuple/list must have length 2, got: {imgsz}')
        img_h = int(imgsz[0])
        img_w = int(imgsz[1])
        if img_h <= 0 or img_w <= 0:
            raise ValueError(f'imgsz entries must be > 0, got: {imgsz}')
        return (img_h, img_w)

    imgsz_int = int(imgsz)
    if imgsz_int <= 0:
        raise ValueError(f'imgsz must be > 0, got: {imgsz}')
    return imgsz_int


def export_tensorrt_engine(
                            model_path: str,
                            engine_out: str | None = None,
                            onnx_out: str | None = None,
                            imgsz: int | tuple[int, int] | list[int] = 1024,
                            device: str = '0',
                            half: bool = True,
                            dynamic: bool = False,
                        ) -> Path:
    """
    Export TensorRT engine from YOLO model path

    # half precision is typically desired for edge inference, but can be disabled for compatibility with older GPUs that lack FP16 support
    # dynamic shape export is typically desired for flexibility, but can be disabled for maximum compatibility
    Supports .pt directly
    """

    if YOLO is None:
        raise ImportError('ultralytics is required for TensorRT export')

    model_path_obj = Path(str(model_path)).expanduser().resolve()
    if not model_path_obj.is_file():
        raise FileNotFoundError(f'model file not found: {model_path_obj}')

    engine_out_obj = None if engine_out is None else Path(str(engine_out)).expanduser().resolve()
    if engine_out_obj is not None:
        engine_out_obj.parent.mkdir(parents = True, exist_ok = True)

    if onnx_out is None and engine_out_obj is not None:
        onnx_out_obj = engine_out_obj.with_suffix('.onnx')
    else:
        onnx_out_obj = None if onnx_out is None else Path(str(onnx_out)).expanduser().resolve()
    if onnx_out_obj is not None:
        onnx_out_obj.parent.mkdir(parents = True, exist_ok = True)

    imgsz_norm = _normalize_imgsz(imgsz)

    export_source = model_path_obj
    export_workspace = None
    if model_path_obj.suffix.lower() == '.pt' and onnx_out_obj is not None:
        # Export from a temp copy whose stem matches the requested ONNX output.
        # This avoids clobbering a sibling <source>.onnx generated by Ultralytics.
        export_workspace = tempfile.TemporaryDirectory(prefix = 'boxinfer_export_')
        export_source = Path(export_workspace.name) / f'{onnx_out_obj.stem}{model_path_obj.suffix.lower()}'
        shutil.copy2(model_path_obj, export_source)

    try:
        # build YOLO wrapper and ask it to export TensorRT engine
        # let ultralytics handle conversion path for .pt and supported .onnx
        model       = YOLO(str(export_source))
        export_out  = model.export(
                                    format = 'engine',
                                    imgsz = imgsz_norm,
                                    device = str(device),
                                    half = bool(half),
                                    dynamic = bool(dynamic),
                                )

        src_engine  = _resolve_engine_path(export_out = export_out, model_path = export_source)
        if export_source.suffix.lower() == '.onnx':
            src_onnx = export_source
        else:
            src_onnx = _resolve_onnx_path(export_source)

        if engine_out_obj is not None and src_engine.resolve() != engine_out_obj.resolve():
            shutil.copy2(src_engine, engine_out_obj)

        if onnx_out_obj is not None and src_onnx.resolve() != onnx_out_obj.resolve():
            shutil.copy2(src_onnx, onnx_out_obj)

        return src_engine if engine_out_obj is None else engine_out_obj
    finally:
        if export_workspace is not None:
            export_workspace.cleanup()


def _parse_args() -> argparse.Namespace:
    # CLI is intentionally minimal for edge-device scripting
    parser = argparse.ArgumentParser(description = 'Export TensorRT engine from YOLO model path')
    parser.add_argument('--model-path', type = str, required = True, help = 'Path to source model (.pt or .onnx)')
    parser.add_argument('--engine-out', type = str, default = None, help = 'Optional explicit .engine output path')
    parser.add_argument('--onnx-out', type = str, default = None, help = 'Optional explicit .onnx output path')
    parser.add_argument('--imgsz', type = int, default = 1024)
    parser.add_argument('--device', type = str, default = '0')
    parser.add_argument('--half', action = 'store_true', help = 'Enable FP16 export')
    parser.add_argument('--dynamic', action = 'store_true', help = 'Enable dynamic shape export')
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    # execute export and print final resolved output path
    out = export_tensorrt_engine(
                                    model_path = args.model_path,
                                    engine_out = args.engine_out,
                                    onnx_out = args.onnx_out,
                                    imgsz = args.imgsz,
                                    device = args.device,
                                    half = bool(args.half),
                                    dynamic = bool(args.dynamic),
                                )
    print(f'Engine export complete: {out}')


if __name__ == '__main__':
    main()


# converting .pt to .engine with ultralytics export helper
# boxinfer-export-trt \
#   --model-path /path/to/model.pt \
#   --engine-out /path/to/model.engine \
#   --imgsz 1024 \
#   --device 0 \
#   --half
# example:
# boxinfer-export-trt \
#   --model-path /home/saa4743/agnc_repos/mae/bbox_inference/test_artifacts/best_fda.pt \
#   --engine-out /home/saa4743/agnc_repos/mae/bbox_inference/test_results/best_fda.engine \
#   --imgsz 1024 \
#   --device 0 \
#   --half
